Sprint 04 app
Vano3d/MovieQuiz-ios pull request #2
Opened 2023-05-29 18:19 UTC by Vano3d

Задача сделана согласно ТЗ.

2023-05-30 19:27 UTC, IBDesignable requested changes
Скругления которые нужно поправить:

<img width="458" alt="Снимок экрана 2023-05-30 в 22 13 39" src="https://github.com/Vano3d/MovieQuiz-ios/assets/121577115/7d37d762-39d2-4f35-9d94-89a5ed52989f">
<img width="458" alt="Снимок экрана 2023-05-30 в 22 13 32" src="https://github.com/Vano3d/MovieQuiz-ios/assets/121577115/37a8ddbe-9f38-43f1-81ef-25e70134f989">

2023-05-30 19:27 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet private var noButton: UIButton!
хорошо!

2023-05-30 19:27 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    }
обычно используем такой порядок: сначала перечисляем свойства класса, затем функции. При этом также делим на приватные и публичные блоки. Функции перечисляют в таком порядке: `init`ы, `override`ы, блоки публичных и приватных функций, и далее блок c аннотацией `@IBAction`

предлагаю поправить

2023-05-30 19:27 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        let action = UIAlertAction(title: alertButtonTitle, style: .default) { [self] _ in
`[self]` - это сильный захват. в замыканиях ссылку на self обычно ослабляют: это помогает избежать утечек памяти. Про это будет в следующих спринтах, а пока предлагаю добавить слово weak `[weak self]` и обращаться через `self?.`

2023-05-30 19:27 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private func showNextQuestionOrResults() {
давай договоримся оставлять не больше одной пустой строки между функциями и другими блоками

2023-05-30 19:27 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +                alertButtonTitle: "Сыграть ещё раз")
guard нужен чтобы отделить ошибки от позитивного сценария. Здесь он использован не по назначению и лучше переписать через if else

2023-05-30 19:27 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            noButton.isEnabled = true
ээти две строчки вероятно будут повторяться очень часто: чтобы их не повторять рекомендую вынести код в новую функцию с параметром

2023-05-30 19:27 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.cornerRadius = 6
скругление не по макету

2023-05-30 19:27 UTC, IBDesignable commented on MovieQuiz/Resources/Base.lproj/LaunchScreen.storyboard
> +                            <imageView clipsSubviews="YES" userInteractionEnabled="NO" contentMode="scaleAspectFit" horizontalHuggingPriority="251" verticalHuggingPriority="251" image="LaunchScreen"
изображение должно иметь такой content mode, чтобы заполнять все пространство. выставляя aspect fit ты говоришь изображению заполнить доступный размер по оси х/y.Такая настройка оставит полоски по бокам для некоторых разрешений. 

Надо поправить

2023-05-30 19:27 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            imageView.layer.borderWidth = 0
после  прохождения раунда у меня остались заблокированными кнопки: не смогла продолжить играть. Нужно найти баг и его устранить

2023-05-30 21:21 UTC, Vano3d commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    }
done

2023-05-30 21:22 UTC, Vano3d commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        let action = UIAlertAction(title: alertButtonTitle, style: .default) { [self] _ in
не получилось с weak, просто убрал сильный захват и проставил self перед свойствами

2023-05-30 21:22 UTC, Vano3d commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +                alertButtonTitle: "Сыграть ещё раз")
done

2023-05-30 21:23 UTC, Vano3d commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            noButton.isEnabled = true
done

2023-05-30 21:23 UTC, Vano3d commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.cornerRadius = 6
done

2023-05-30 21:23 UTC, Vano3d commented on MovieQuiz/Resources/Base.lproj/LaunchScreen.storyboard
> +                            <imageView clipsSubviews="YES" userInteractionEnabled="NO" contentMode="scaleAspectFit" horizontalHuggingPriority="251" verticalHuggingPriority="251" image="LaunchScreen"
done

2023-05-30 21:23 UTC, Vano3d commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            imageView.layer.borderWidth = 0
fixed

2023-05-31 18:44 UTC, IBDesignable approved these changes

2023-05-31 18:44 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private func isEnabledButton(_ isEnabled: Bool) {
```suggestion
    }
    
    private func isEnabledButton(_ isEnabled: Bool) {
```

2023-05-31 18:44 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private func isEnabledButton(_ isEnabled: Bool) {
методы которые начинаются "с вопроса"/"утверждения" (is/should) обычно сопровождаются результатом.
То есть `isEnabledButton() -> Bool`

Здесь же происходит действие: `updateEnablingButtons(_ isEnabled: Bool)` - как пример, можно подобрать и удачнее варианты)

2023-05-31 18:44 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            self.isEnabledButton(true)
Можно попробовать так, когда пройдешь тему в следующих спринтах: 
```swift
        let action = UIAlertAction(title: alertButtonTitle, style: .default) { [weak self] _ in
            self?.resetGame() 
         }
         ....
     ----
     private func resetGame() {
           currentQuestionIndex = 0
            let firstQuestion = questions[currentQuestionIndex]
            let viewModel =  convert(model: firstQuestion)
            show(quiz: viewModel)
             correctAnswers = 0
             imageView.layer.borderWidth = 0
             isEnabledButton(true)
    }

```

2023-05-31 18:44 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
>              currentQuestionIndex += 1
хорошо!

2023-05-31 18:44 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.cornerRadius = 20
отлично

2023-05-31 20:53 UTC, merged